apiVersion: batch/v1
kind: Job
metadata:
  name: anstest1
  namespace: xpp
spec:
  selector: {}
  template:
    metadata:
      name: anstest1
    spec:
      containers:
        - name: cloud-security-toolbox
          image: mss-docker.artifactory.swg-devops.com/tab-pcc-oc-chart:0.0.1-test.e99dff01
          env: 
          - name: GIT_SSH_COMMAND
            value: 'ssh -i /tmp/ssh/ssh-privatekey'
          command: [ "/bin/sh", "-c" ]
          args:
            -
              mkdir ~/.ssh;
              ssh-keyscan github.ibm.com >> ~/.ssh/known_hosts;
              git clone -b test git@github.ibm.com:managed-security/tab-pcc-oc-chart.git /tmp/playbook;
              ansible-playbook /tmp/playbook/ansible_install.yml -e 'ansible_python_interpreter=/usr/bin/python3 custId=ocpjenkins_1629714535848 projPath=ocpjenkins_1629714535848_installation_prisma'
              ## ansible-playbook /tmp/playbook/XXXXXXXXXXX.yaml;
          volumeMounts:
          - name: ssh-deployment-key
            mountPath: "/tmp/ssh/"
            readOnly: true
      restartPolicy: Never
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      volumes:
      - name: ssh-deployment-key
        secret:
          secretName: manoj-ssh
          defaultMode: 0600