{{- if .Values.openshift }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: twistlock-console
users:
- system:serviceaccount:{{ .Values.namespace }}:twistlock-console
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
allowPrivilegedContainer: false
fsGroup: # Volumes which support ownership management are modified to be owned and writable by the GID specified in fsGroup
  type: RunAsAny
# Value 0 is the same as null from OpenShift docs and is set so validation succeeds
priority: 0
readOnlyRootFilesystem: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups: # Supplemental groups are regular Linux groups. When a process runs in Linux, it has a UID, a GID, and one or more supplemental groups.
  type: RunAsAny
volumes:
- '*' # Types of volumes the pod can mount. * is wildcard. https://docs.openshift.org/latest/architecture/additional_concepts/authorization.html#authorization-controlling-volumes
{{- end}}